### ISSUE TITLE
localhost to live server

### ISSUE THREAD

**Issue by lucasvieirawerner** [javathunderman/retinopathy-server#1]
Hello, tested it locally and is working fine

do you have any tip in how to install it in a server, i'm using aws ec2+apache with the following .htacess

`WSGIApplicationGroup %{GLOBAL}
SetEnv no-gzip 1
<VirtualHost *:80>
        <Directory /var/www/html>
                Options +ExecCGI
                DirectoryIndex update.py
        </Directory>
        AddHandler cgi-script .py
        ServerAdmin lucaswerner@alunos.utfpr.edu.br
        DocumentRoot /var/www/html
        ErrorLog /var/www/html/error.log
        CustomLog /var/www/html/access.log combined
</VirtualHost>`

but it just stay loading

**Comment by lucasvieirawerner** [comment]
![504 gateway timeout](https://user-images.githubusercontent.com/11530373/40394647-ac1619b4-5dfa-11e8-9453-f33eb17a631e.png)

**Comment by lucasvieirawerner** [comment]
`[Tue May 22 22:50:25.679098 2018] [cgi:warn] [pid 4773] [client 168.181.48.80:33698] AH01220: Timeout waiting for output from CGI script /var/www/html/upload.py, referer: http://52.40.154.177/
[Tue May 22 22:50:25.679158 2018] [cgi:error] [pid 4773] [client 168.181.48.80:33698] Script timed out before returning headers: upload.py, referer: http://52.40.154.177/
[Tue May 22 22:55:25.752642 2018] [cgi:warn] [pid 4773] [client 168.181.48.80:33698] AH01220: Timeout waiting for output from CGI script /var/www/html/upload.py, referer: http://52.40.154.177/`

**Comment by lucasvieirawerner** [comment]
# Error.log

[Tue May 22 22:50:25.679098 2018] [cgi:warn] [pid 4773] [client 168.181.48.80:33698] AH01220: Timeout waiting for output from CGI script /var/www/html/upload.py, referer: http://52.40.154.177/

[Tue May 22 22:50:25.679158 2018] [cgi:error] [pid 4773] [client 168.181.48.80:33698] Script timed out before returning headers: upload.py, referer: http://52.40.154.177/

[Tue May 22 22:55:25.752642 2018] [cgi:warn] [pid 4773] [client 168.181.48.80:33698] AH01220: Timeout waiting for output from CGI script /var/www/html/upload.py, referer: http://52.40.154.177/

**Comment by javathunderman** [comment]
Hi there, thanks for reaching out. Will look up the server configuration and get back to you.

**Comment by lucasvieirawerner** [comment]
ok

**Comment by javathunderman** [comment]
@lucasvieirawerner We use NGINX for our server and I can't quite remember how our configuration would would work with Apache, but this configuration file might help. You can usually drop it in your /etc/sites-available directory. We're using virtual hosts (not managed with the .htaccess file) to pass requests to the upload.py file. 

```
## Retinopathy Reverse-Proxy
## This contains the reverse proxy for retinopathy.nomik.xyz

# HTTP
server {
	listen 80;
	listen [::]:80;

	server_name retinopathy.nomik.xyz;

	return 301 https://$server_name$request_uri;
}

# HTTPS
server {
	listen 443 ssl;
	listen [::]:443 ssl;

	ssl on;
        ssl_certificate nomik-https-cert.pem;
        ssl_certificate_key nomik-https-key.key;

	server_name retinopathy.nomik.xyz;

	location / {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_pass http://localhost:8000;
	}
}

```

[This](https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html) might help with implementing reverse proxies/virtual hosts on Apache. Let us know if you need more help.

**Comment by lucasvieirawerner** [comment]
ok, gonna try with ngix

**Comment by lucasvieirawerner** [comment]
trying to implement using nginx, is there any specific configuration, trying to use as the example but is not working

**Comment by javathunderman** [comment]
Hi, sorry for the late response. If you're using NGINX you can try using [this](https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04) tutorial from Digital Ocean. In place of step 3 in that tutorial, you can use the server config that I posted above. Once the server is up and running, you can run the upload.py file and it should appear on the web. You may also want to use [systemd](https://www.devdungeon.com/content/creating-systemd-service-files) or some other daemon in order to keep upload.py running in the background. 

Again, let me know if you need more help. For me, server configuration was harder than actually writing the actual project.

**Comment by javathunderman** [comment]
@lucasvieirawerner ping! Need any more help?

**Comment by lucasvieirawerner** [comment]
sorry for the delay,
Did the tutorial and added the following config:

```
server {
    listen       80;
    server_name  localhost;
    access_log  /var/log/nginx/proxy-apache.log;

   
	location / {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_pass http://localhost:8000;
	}
}

```

runned $python upload.py

working fine

**Comment by lucasvieirawerner** [comment]
was missing 
`client_max_body_size 3M;`
in 
`$ sudo nano /etc/nginx/nginx.conf`

**Comment by lucasvieirawerner** [comment]
Now i'm having problem with the systemctl, running manually doesn't happen any error, but running with systemctl happens that:

```
● myapp.service
   Loaded: loaded (/etc/systemd/system/myapp.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-06-11 13:49:58 UTC; 2s ago
  Process: 14241 ExecStart=/home/ubuntu/myapp.sh (code=exited, status=1/FAILURE)
 Main PID: 14241 (code=exited, status=1/FAILURE)

Jun 11 13:49:57 ip-172-31-21-111 systemd[1]: Started myapp.service.
Jun 11 13:49:58 ip-172-31-21-111 myapp.sh[14241]: Traceback (most recent call last):
Jun 11 13:49:58 ip-172-31-21-111 myapp.sh[14241]:   File "/var/www/html/upload.py", line 18, in <module>
Jun 11 13:49:58 ip-172-31-21-111 myapp.sh[14241]:     import cleanup
Jun 11 13:49:58 ip-172-31-21-111 myapp.sh[14241]:   File "/var/www/html/cleanup.py", line 4, in <module>
Jun 11 13:49:58 ip-172-31-21-111 myapp.sh[14241]:     from path import Path
Jun 11 13:49:58 ip-172-31-21-111 myapp.sh[14241]: ImportError: No module named path
```
tried to:

`pip install path.py`

but the error still happen

**Comment by lucasvieirawerner** [comment]
myapp.sh:

```

#!/bin/bash
python /var/www/html/upload.py

```
myapp.service:

```

[Service]
ExecStart=/home/ubuntu/myapp.sh

```

**Comment by lucasvieirawerner** [comment]
pip list:

```
Package           Version    
----------------- -----------
absl-py           0.2.2      
astor             0.6.2      
backports.weakref 1.0.post1  
bleach            1.5.0      
enum34            1.1.6      
funcsigs          1.0.2      
futures           3.2.0      
gast              0.2.0      
grpcio            1.12.0     
html5lib          0.9999999  
Markdown          2.6.11     
mock              2.0.0      
numpy             1.14.3     
path.py           11.0.1     
pbr               4.0.3      
pip               10.0.1     
protobuf          3.5.2.post1
setuptools        20.7.0     
six               1.11.0     
tensorboard       1.8.0      
tensorflow        1.8.0      
termcolor         1.1.0      
virtualenv        16.0.0     
Werkzeug          0.14.1     
wheel             0.29.0
```

**Comment by javathunderman** [comment]
@lucasvieirawerner This is what we have for our systemd config file (myapp.service). No need for a bash script or anything like that. 

````
[Unit]
Description=Retinopathy Server
After=network.target

[Service]
Type=simple
User=javathunderman
ExecStart=/usr/bin/python /home/.../upload.py
Restart=always
WorkingDirectory=/home/.../retinopathy-server
[Install]
WantedBy=multi-user.target
`

**Comment by lucasvieirawerner** [comment]
changed, but still with:

```
● myapp.service
   Loaded: loaded (/etc/systemd/system/myapp.service; static; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2018-06-11 22:16:29 UTC; 3s ago
  Process: 15569 ExecStart=/usr/bin/python /var/www/html/upload.py (code=exited, status=1/FAILURE)
 Main PID: 15569 (code=exited, status=1/FAILURE)

Jun 11 22:16:28 ip-172-31-21-111 systemd[1]: Started myapp.service.
Jun 11 22:16:28 ip-172-31-21-111 python[15569]: Traceback (most recent call last):
Jun 11 22:16:28 ip-172-31-21-111 python[15569]:   File "/var/www/html/upload.py", line 18, in <module>
Jun 11 22:16:28 ip-172-31-21-111 python[15569]:     import cleanup
Jun 11 22:16:28 ip-172-31-21-111 python[15569]:   File "/var/www/html/cleanup.py", line 4, in <module>
Jun 11 22:16:28 ip-172-31-21-111 python[15569]:     from path import Path
Jun 11 22:16:28 ip-172-31-21-111 python[15569]: ImportError: No module named path
Jun 11 22:16:29 ip-172-31-21-111 systemd[1]: myapp.service: Main process exited, code=exited, status=1/FAILURE
Jun 11 22:16:29 ip-172-31-21-111 systemd[1]: myapp.service: Unit entered failed state.
Jun 11 22:16:29 ip-172-31-21-111 systemd[1]: myapp.service: Failed with result 'exit-code'.

```
is the path.py in the right version?

`path.py           11.0.1 `

**Comment by javathunderman** [comment]
@lucasvieirawerner Are you sure you're using Python 2.7? (specifically 2.7.12)?

**Comment by lucasvieirawerner** [comment]
![screenshot from 2018-06-11 19-21-54](https://user-images.githubusercontent.com/11530373/41260188-cd326b72-6dac-11e8-80cf-c193d384c3de.png)

**Comment by lucasvieirawerner** [comment]
the strange thing is if i ran it manually works perfect, but when i run using systemctl happens that error

**Comment by lucasvieirawerner** [comment]
erased pip and reinstalled, running now

**Comment by lucasvieirawerner** [comment]
![149656](https://user-images.githubusercontent.com/11530373/41265064-a43969ea-6dc6-11e8-9304-341bcb7aea66.jpg)

**Comment by javathunderman** [comment]
@lucasvieirawerner Awesome!
